sourceTxtFilePath: "/Users/zhuxiuwei/Downloads/需要屏蔽的图书.txt"
targetExcelPath: "/Users/zhuxiuwei/Downloads"
printClassAndFields:
  - className: "tools.bookTxt2Excel.bean.BookWithStingFields"
    fields:
      - "ISBN"
      - "作品语种"
      - "题名"
      - "版本"
      - "出版信息"
      - "稽核项"
      - "一般注"
      - "论题主题"
      - "个人名称等同知识责任"
      - "丛书"
      - "目次备注"
      - "概要"
      - "个人主题"
      - "变异题名"
      - "题名主题"
      - "versions"
  - className: "tools.bookTxt2Excel.bean.Version"
    fields:
      - "versionNumber"
      - "copies"
  - className: "tools.bookTxt2Excel.bean.Copy"
    fields:
      - "复本号"
      - "标识"
      - "馆别"
      - "价格"
      - "文献类别1"
      - "文献类别2"
      - "类型"
      - "永久馆藏位置"
      - "已新增"
      - "目前馆址"
      - "件"
      - "cat3"
      - "cat4"
      - "cat5"
      - "馆藏期限"
bottomClassName: "tools.bookTxt2Excel.bean.Copy"
